// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Nohai.Data;

namespace Proiect_Nohai.Migrations
{
    [DbContext(typeof(Proiect_NohaiContext))]
    [Migration("20200102134449_AddedFKBileteClienti")]
    partial class AddedFKBileteClienti
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proiect_Nohai.Models.Bilet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BileteCumparate")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataJocului")
                        .HasColumnType("datetime2");

                    b.Property<string>("EchipaGazda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EchipaOaspete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("ID");

                    b.HasIndex("ClientID")
                        .IsUnique();

                    b.ToTable("Bilet");
                });

            modelBuilder.Entity("Proiect_Nohai.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NumeClient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReducereID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ReducereID")
                        .IsUnique();

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Proiect_Nohai.Models.Reducere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipReducere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Reducere");
                });

            modelBuilder.Entity("Proiect_Nohai.Models.Bilet", b =>
                {
                    b.HasOne("Proiect_Nohai.Models.Client", "Client")
                        .WithOne("Bilet")
                        .HasForeignKey("Proiect_Nohai.Models.Bilet", "ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proiect_Nohai.Models.Client", b =>
                {
                    b.HasOne("Proiect_Nohai.Models.Reducere", "Reducere")
                        .WithOne("Client")
                        .HasForeignKey("Proiect_Nohai.Models.Client", "ReducereID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
